### ISSUE TITLE
Creating any machine then placing causes it to duplicate

### ISSUE THREAD

**Issue by 8BrickDMG** [thebrightspark/S.T.E.M#1]
When you craft any of the machines and place them down, the same spot in your inventory adds the same machine back.

If you try to place this block, it kicks you from a SMP server.

The only way to get back on is to restart the server otherwise it will error saying the host has removed you etc.

**Comment by 8BrickDMG** [comment]
Tested in a server environment.

**Comment by thebrightspark** [comment]
Fixed by commit https://github.com/thebrightspark/S.T.E.M/commit/5472d4e1c2827131efb4345172299d7baf0dd049
