### ISSUE TITLE
Sugestion: Generator and Commannd

### ISSUE THREAD

**Issue by CTH999** [thebrightspark/S.T.E.M#11]
It would be cool if you could turn the STEM fluid back into the same amount of rf, meaning if it takes 100000rf to make 1 mb, you can use 1mb to get 100000rf. meaning a small fluid tank can store a lot of energy!

It would also be cool if there was a command that you could use to add in the recipe. (I.E. you could hold stone in you hand, and type the command along with how much it costs, and it adds it to the configs!) Then with another command it would reload the configs, or you might just have to restart the game. This is useful if you don't know the item id of silver from Thermal expansion.

Just a sugestion

**Comment by thebrightspark** [comment]
I don't know about turning the fluid back into energy... maybe that could be an addon instead? (that's open for anyone to make if they want).

There already are commands for adding recipes for the item you're holding.
Type `/stem` for all of the commands.

**Comment by CTH999** [comment]
Ok, Thanks!
