### ISSUE TITLE
Cant give RF/FE to the Machines

### ISSUE THREAD

**Issue by Xaikii** [thebrightspark/S.T.E.M#12]
Well the title says it all, in short from:

I am trying to power my machine / wanna check out what this Mod can... well I can't none of the machines can be powered. Normally Machines should be able to suck Energy from a Battery right next to them, since Batteries are outputing Energy. I even tried to power them with cables what ended as a Fail again.

Mods I tried as Battery and Cables
IntegratedDynamics & HammerCore

Versions:
S.T.E.M: 1.12.2-0.1.3
Forge: 14.23.2.2615
RedstoneFlux: 1.12-2.0.1.2

**Comment by thebrightspark** [comment]
It's probably the energy mods you're using. I've been using STEM fine with larger mods like Thermal Expansion with Thermal Dynamics and Draconic Evolution. I will look into it with this mod when I have time, but know that other energy mods do work.
