### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by Fortist** [thebrightspark/S.T.E.M#13]
It seems like only hoppers work with taking items out, however it also takes out the memory chip.

**Comment by thebrightspark** [comment]
I've made a change in commit https://github.com/thebrightspark/S.T.E.M/commit/03f9ec039033f328d52eb981130c63fb6583c30d to hopefully allow other blocks to pull items from the machines, although I'm not sure what you'd want about taking out the memory chip.

If you want to automate the machines, wouldn't you want control over the memory chips as well? You can just use mods with filters on what they can pull out.

**Comment by Fortist** [comment]
I'd want it to not pull out the memory chip. 
I mean, why not take out both iron ore and ingots from the furnace from one side? 
Could just filter it.
