### ISSUE TITLE
Inserting a memory chip into a scanner storage crashes client

### ISSUE THREAD

**Issue by 8BrickDMG** [thebrightspark/S.T.E.M#2]
[crash-2017-10-22_23.34.44-client.txt](https://github.com/thebrightspark/S.T.E.M/files/1584511/crash-2017-10-22_23.34.44-client.txt)

**Comment by 8BrickDMG** [comment]
Tested in a server environment.

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/S.T.E.M/commit/de50958688c0557dfd0508372e15c87288c2ea7a
