### ISSUE TITLE
Recipe file and recipe added by command conflict

### ISSUE THREAD

**Issue by 8BrickDMG** [thebrightspark/S.T.E.M#3]
If you have added a recipe for the matter scanner using /stem add *liquid amount* and then after have inputted manually into the recipe file for the same item/block.

The one done with the command takes precedence first.

Resolution is to remove it with /stem remove *block/item name* and then refresh the server.

**Comment by 8BrickDMG** [comment]
Tested in a server environment.

**Comment by 8BrickDMG** [comment]
To replicate, add a recipe with the command.

Check if it works in the matter scanner.

Stop the server.

Tweak the same recipe in the recipe file and restart the server.

**Comment by thebrightspark** [comment]
Sounds like a sync issue. Need to invalidate the client cache when joining a server.

**Comment by thebrightspark** [comment]
Should be fixed in commit https://github.com/thebrightspark/S.T.E.M/commit/07d297dcb5723b28e0f9a5cc6901934668329481
