### ISSUE TITLE
Memory Chip: Empty Output Slot

### ISSUE THREAD

**Issue by 8BrickDMG** [thebrightspark/S.T.E.M#4]
![2017-12-24_18 14 03](https://user-images.githubusercontent.com/7628776/34328405-c72db35e-e8d6-11e7-9c8b-493144410058.png)

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/S.T.E.M/commit/876cb6e0d24cb3891064f6499686d559efd2a549
