### ISSUE TITLE
/stem generate server error

### ISSUE THREAD

**Issue by 8BrickDMG** [thebrightspark/S.T.E.M#5]
![capture](https://user-images.githubusercontent.com/7628776/34328533-d93ea0a6-e8d8-11e7-811e-b42026e3e243.PNG)
![2017-12-24_18 19 52](https://user-images.githubusercontent.com/7628776/34328526-b12d902c-e8d8-11e7-9dfb-c20cd5d5f22a.png)

**Comment by thebrightspark** [comment]
Fixed in commit https://github.com/thebrightspark/S.T.E.M/commit/49d9ecf1793279729d8a2d078874d151808befea
