### ISSUE TITLE
The GUI will not become black

### ISSUE THREAD

**Issue by SihenZhang** [thebrightspark/S.T.E.M#9]
Minecraft Version: 1.12.2
Forge Version: 14.23.1.2586
Mod Version: 0.1.2
Singleplayer/Multiplayer: Singleplayer

Additional Information:
![](https://i.imgur.com/5biIuTm.png)

**Comment by thebrightspark** [comment]
Ah yes I remember noticing this recently. It's an issue from porting to 1.12.
Will look into it when I'm working on the mod next.

FYI you also won't see item tooltips either, which is a related issue.

**Comment by thebrightspark** [comment]
Fixed in https://github.com/thebrightspark/S.T.E.M/commit/c151c9b255cd3733b63a681bdd667ea8df5a12b6
